### ISSUE TITLE
redirect

### ISSUE THREAD

**Issue by tejasmanohar** [simplyianm/resume#3]
https://github.com/simplyianm/resume/blob/master/index.html#L1

should be using HTML `meta http-equiv` for redirects

```html
<meta http-equiv="refresh" content="0; url=http://ian.pw/resume" />
```

or even better, cloudflare's page rules!

**Comment by simplyianm** [comment]
Thanks man! I appreciate it. I'll look into this soon! :capital_abcd:

**Comment by tejasmanohar** [comment]
In reality, cloudflare redirects are fastest and best tho since search engines understand that they're permanent redirects BUT yeah this is better than that js
